apiVersion: v1
kind: Service
metadata:
  name: rpi-lcd-react
  namespace: rpi-lcd
  labels:
    service: rpi-lcd-react
spec:
  type: NodePort
  selector:
    app: rpi-lcd-react
    tier: frontend
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 32000
