apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: rpi-lcd 
  labels:
    app: rpi-lcd
    tier: backend
    worker: $NODE_SELECTOR
spec:
  containers:
    - name: rpi-container 
      image: sktrinh12/rpi-fastapi-ubuntu:latest
      ports:
      - containerPort: 8000
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /dev/i2c-1
        name: i2c 
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SVC
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: $NODE_SELECTOR
  volumes:
  - name: i2c
    hostPath:
      path: /dev/i2c-1
