apiVersion: v1
kind: Service
metadata: 
  name: $SVC_NAME 
  namespace: rpi-lcd
spec:
  type: NodePort
  selector: 
    tier: backend
    app: rpi-lcd
    worker: $NODE_SELECTOR
  ports: 
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: $NODE_PORT
