apiVersion: v1
kind: Service
metadata: 
  name: rpi-lcd-svc 
  namespace: rpi-lcd
spec:
  type: NodePort
  selector: 
    tier: backend
    component: rpi-lcd
  ports: 
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 31000
